# Generated by Django 4.0.4 on 2022-05-21 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('postTitle', models.CharField(max_length=255)),
                ('postContent', models.TextField()),
                ('postDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmarket.user')),
            ],
        ),
    ]
