# Generated by Django 4.0.4 on 2022-07-08 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0004_alter_bookmark_stockticker_bookmark_unique_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('subreddit', models.CharField(max_length=225, unique=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
