# Generated by Django 4.0.4 on 2022-07-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0005_scrapingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingmodel',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
