# Generated by Django 4.0.4 on 2022-07-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0006_alter_scrapingmodel_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingmodel',
            name='packagedData',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='scrapingmodel',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
