# Generated by Django 4.0.4 on 2022-07-18 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0007_scrapingmodel_packageddata_alter_scrapingmodel_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
