# Generated by Django 4.0.4 on 2022-07-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0008_upcomingearnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingearnings',
            name='processedData',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='upcomingearnings',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
